Create hash-table.h
ProfessorLayton322/hash-table pull request #1
Opened 2021-03-09 11:19 UTC by ProfessorLayton322

Код хэш таблицы
Фёдор Быков 201
https://official.contest.yandex.ru/contest/24924/run-report/49046502/

2021-06-22 21:38 UTC, glebshp requested changes

2021-06-22 21:38 UTC, glebshp commented on hash-table.h
> +It doubles the table size if needed to expand.
А за счёт чего линейное итерирование? Описание недостаточное

2021-06-22 21:38 UTC, glebshp commented on hash-table.h
> +Check https://pastebin.com/esx8ckYw for more.
Зачем это вставлено через pastebin?

2021-06-22 21:38 UTC, glebshp commented on hash-table.h
> +*/
Не хватает ссылки на полноценное описание реализации, например на википедию

2021-06-22 21:38 UTC, glebshp commented on hash-table.h
> +  private:
приватные поля идут в конце, никак не до публичных методов

2021-06-22 21:38 UTC, glebshp commented on hash-table.h
> +        capacity *= 2;
Управляющая константа 2 должна быть вынесена в константное поле класса

2021-06-22 21:38 UTC, glebshp commented on hash-table.h
> +            int hash = hasher(it->first) % capacity;
почему int ?

2021-06-22 21:38 UTC, glebshp commented on hash-table.h
> +        if (size() == capacity) {
Действие "проверь нормальный ли размер, и, если надо, увеличь" явно нужно вынести в отдельный метод

2021-06-22 21:38 UTC, glebshp commented on hash-table.h
> +    size_t size() const {
а почему стиль именования публичных методов не отличается от стиля именования приватных полей?

2021-06-22 21:38 UTC, glebshp commented on hash-table.h
> +        capacity(std::distance(inputBegin, inputEnd)),
такое решение не будет работать с однопроходными итераторами

2021-06-22 21:38 UTC, glebshp commented on hash-table.h
> +        table(std::distance(inputBegin, inputEnd)),
и почему мы сразу делаем таблицу с таким capacity, что после заполнения её придётся перестраивать?

2021-06-22 21:38 UTC, glebshp commented on hash-table.h
> +            if (input.begin() == input.end()) {
выравнивание

2021-06-22 21:38 UTC, glebshp commented on hash-table.h
> +        for (auto it = input.begin(); it != input.end(); ++it) {
почему не range-based for?

2021-06-22 21:38 UTC, glebshp commented on hash-table.h
> +                if (contentIt->first == it->first)
нет фигурных скобок после if

2021-06-22 21:38 UTC, glebshp commented on hash-table.h
> +            if (flag)
и тут нет скобок

2021-06-22 21:38 UTC, glebshp commented on hash-table.h
> +            for (iterator contentIt : table[hash])
почему не константный итератор?

2021-06-22 21:38 UTC, glebshp commented on hash-table.h
> +            for (auto it = content.begin(); it != content.end(); ++it) {
опять же можно range-based for

2021-06-23 11:57 UTC, ProfessorLayton322 commented on hash-table.h
> +            for (auto it = content.begin(); it != content.end(); ++it) {
Нет нельзя, мне нужен итератор чтобы закинуть его дальше в таблицу

2021-06-23 22:19 UTC, glebshp requested changes

2021-06-23 22:19 UTC, glebshp commented on hash-table.h
> +        checkExpansion();
очень странно, почему мы сначала увеличиваем счётчик, потом пробуем отмасштабироваться, потом вставляем элемент? Вроде checkExpansion должен быть в конце

2021-06-23 22:19 UTC, glebshp commented on hash-table.h
> +        bool flag = false;
это дублирование кода find, почему бы не использовать его здесь?

2021-06-23 22:19 UTC, glebshp commented on hash-table.h
> +        if (size() == _capacity) {
вроде бы всё равно, но идейно правильнее написать >=

2021-06-23 22:19 UTC, glebshp commented on hash-table.h
> +        for (size_t i = 0; i < my_size; i++)
скобки

2021-06-23 22:19 UTC, glebshp commented on hash-table.h
> +        _table.resize(_capacity);
получается, мы сразу создаём переполненную таблицу?

2021-06-24 20:46 UTC, glebshp requested changes

2021-06-24 20:46 UTC, glebshp commented on hash-table.h
> +        auto _it = other.begin();
не понятно что тут происходит, либо зарефакторить, либо добавить комменты

2021-06-25 18:54 UTC, glebshp approved these changes

2021-06-25 19:00 UTC, merged